variables:
  REPO_NAME: git@git.techvify.com.vn:evp/phase2/ecommit2-fe.git

stages:
  - before_script
  - test
  - build
  - deploy

Before_Script:
  stage: before_script
  script:
    - echo $CI_COMMIT_TAG
  variables:
    GIT_CLONE_PATH: "$CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_PATH"
  only:
    refs:
      - main
  tags:
    - ecommit2fe

Test:
  stage: test
  script:
    - npm i eslint && npm run lint
  tags:
    - ecommit2fe

# Just for Dev Env
Build QA:
  stage: build
  only:
    - develop
  needs: [Test]
  script:
    - npm install && npm run build-only
  artifacts:
    paths:
      - dist
  variables:
    GIT_Build_PATH: "$CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_PATH"
  tags:
    - ecommit2fe
  when: manual

Deploy QA:
  stage: deploy
  only:
    - develop
  needs: [Build QA]
  script:
    - aws s3 rm s3://eco-value.jp/assets/ --recursive
    - aws s3 sync ./dist/ s3://eco-value.jp
    - aws cloudfront create-invalidation --distribution-id E1MEU6Y19FXVBO --paths "/*"
  variables:
    GIT_Build_PATH: "$CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_PATH"
  tags:
    - ecommit2fe
  when: manual

# Just for Uat Env

Build UAT:
  stage: build
  only:
    - /^release.*$/
  needs: [Test]
  script:
    - npm install && npm run build-uat-only
  artifacts:
    paths:
      - dist
  variables:
    GIT_Build_PATH: "$CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_PATH"
  tags:
    - ecommit2fe
  when: manual

Deploy UAT:
  stage: deploy
  only:
    - /^release.*$/
  needs: [Build UAT]
  script:
    - aws s3 rm s3://qa.eco-value.jp/assets/ --recursive
    - aws s3 sync ./dist/ s3://qa.eco-value.jp
    - aws cloudfront create-invalidation --distribution-id E1OYMW78KG68YQ --paths "/*"
  variables:
    GIT_Build_PATH: "$CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_PATH"
  tags:
    - ecommit2fe
  when: manual
