export const routeNames = {
  default: "DEFAULT",
  notFound: "PAGE_NOT_FOUND",
  login: "AUTH_LOGIN",
  forgotPassword: "FORGOT_PASSWORD",
  collectionBusiness: "COLLECTION_BUSINESS",
  productManufacture: "PRODUCT_MANUFACTURE",
  traceability: "TRACEABILITY",
  customerManagement: "CUSTOMER_MANAGEMENT",
  verhicleManagement: "VERHICLE_MANAGEMENT",
  realTimeDynamics: "REAL_TIME_DYNAMICS",
  vehicle: "VEHICLE",
  createVehicle: "CREATE_VEHICLE",
  editVehicle: "EDIT_VEHICLE",
  vehicleType: "VEHICLE_TYPE",
  createVehicleType: "CREATE_VEHICLE_TYPE",
  editVehicleType: "EDIT_VEHICLE_TYPE",
  staffManagement: "STAFF_MANAGEMENT",
  container: "CONTAINER",
  containerChild: "CONTAINER_CHILD",
  containerType: "CONTAINER_TYPE",
  createContainerType:"CREATE_CONTAINER_TYPE",
  workingPlace: "WORKING_PLACE",
  setting: "SETTING"
};
