variables:
  REPO_NAME: git@git.techvify.com.vn:evp/phase2/ecommit2-fe.git
stages:
  - before_script
  - test
  - build
  - deploy

Before_Script:
  stage: before_script
  script:
    - npm i eslint
  variables:
    GIT_CLONE_PATH: "$CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_PATH"
  only:
    refs:
      - main
  tags:
    - ecommit2fe

Test Dev:
  stage: test
  script:
    - echo "Test Dev Env"
  tags:
    - ecommit2fe

Build Dev:
  stage: build
  needs: [Test Dev]
  script:
    - echo "Build Dev Env"
  tags:
    - ecommit2fe
  when: manual

Deploy Dev:
  stage: deploy
  only:
    - /^release.*$/
  needs: [Build Dev]
  script:
    - echo "Deploy Dev Env"
  tags:
    - ecommit2fe
  when: manual
