export enum TypeOptions {
  TENANT = 1,
  PARTNER = 2,
  CUSTOMER = 3,
  DESTINATION = 4
}

export enum UserRoleOptions {
  SYSTEM_ADMIN = 1,
  TENANT_ADMIN = 2,
  PARTNER_ADMIN = 2,
  COLLECTION_BASE_ADMIN = 3,
  DISCHARGER = 4,
  DASHBOARD_USER = 5,
  CONSIGNEE = 6,
  DRIVER = 7,
  MANUFACTURING_STAFF = 8,
  DRIVER_MANUFACTURING_STAFF = 9
}

export enum TypeWorkPlace {
  COLLECTION_BASE = 1,
  TENANT_ADMIN = 2,
  CUSTOMER = 3,
  TENANT_DESTINATION = 4,
  DISPOSAL = 5
}
