import mitt from "mitt";
const emitter = mitt();

export const EMITTER_EVENTS = {
  TOGGLE_SIDE_BAR: "TOGGLE_SIDE_BAR",
  SELECT_COLLECT_ROUTE_REFERENCE_DATA: "SELECT_COLLECT_ROUTE_REFERENCE_DATA",
  SHOW_COLLECT_ROUTE_REFERENCE_DATA: "SHOW_COLLECT_ROUTE_REFERENCE_DATA",
};
export default emitter;
